### ISSUE TITLE
Not able to use pause menu to return back to main menu (Both in sink and bin level)

### ISSUE THREAD

**Issue by APODICTIC** [Sturdge/Splash-Dash#148]
Type: Major

Repeatable: Every time

Steps to reproduce: 
1. Open the game
2. Select characters
3. Get sink or bin level
4. Try quitting the game while in the game.

Screenshot:

![image](https://user-images.githubusercontent.com/56399859/77858004-c1794600-71f8-11ea-93fd-685bb33b870e.png)

Description: Player can’t exit to main menu by using the pause menu. This happens in bin and sink level only.

**Comment by APODICTIC** [comment]
for all levels

**Comment by Danny-HypnoTank** [comment]
Has been fixed was due to timescale still being set to 0 so game was still paused
