### ISSUE TITLE
No players spawning in fridge level (same for sink)

### ISSUE THREAD

**Issue by APODICTIC** [Sturdge/Splash-Dash#173]
Name of Bug: No players spawning in fridge level (same for sink)

Type: Game Breaker

Repeatable: Every time

Steps to reproduce: 
1. Open the game
2. Select characters
3. Select sink or fridge level

Screenshot:

![image](https://user-images.githubusercontent.com/56399859/78580357-3583a180-782a-11ea-90af-72c28c187341.png)
![image](https://user-images.githubusercontent.com/56399859/78580370-387e9200-782a-11ea-96ed-aa2a5c705a6a.png)

Description: Players aren’t spawning in fridge and sink level after starting the game. Something to do with player prefab not getting activated and locked in.

**Comment by APODICTIC** [comment]
build version isn't spawning characters in all levels.

**Comment by Danny-HypnoTank** [comment]
Player spawn correct and inside the level
