### ISSUE TITLE
Splat texture too low making it look weird (in bin level)

### ISSUE THREAD

**Issue by APODICTIC** [Sturdge/Splash-Dash#216]
Name of Bug: Splat texture too low making it look weird (in bin level)

Type: Minor

Repeatable: Yes

Steps to Reproduce: 1. Open the game
                                     2. Select characters
                                     3. Select Bin level
                                     4. Try painting the bin level

Screenshot:
![image](https://user-images.githubusercontent.com/56399859/79765581-b5c3ff80-831e-11ea-8546-84def726f97f.png)

Description: This is merely a texture resolution issue for splatting and painting the environment. Increasing splat texture resolution should fix it.

**Comment by Danny-HypnoTank** [comment]
SPlat textures have been reworked to be higher resolution
