### ISSUE TITLE
Mass drop isn’t accessible in bin level

### ISSUE THREAD

**Issue by APODICTIC** [Sturdge/Splash-Dash#217]
Name of Bug: Mass drop isn’t accessible in bin level

Type: Minor

Repeatable: Yes

Steps to Reproduce: 1. Open the game
                                     2. Select characters
                                     3. Select Bin level
                                     4. Try using mass dropper

Screenshot:
![image](https://user-images.githubusercontent.com/56399859/79765712-e1df8080-831e-11ea-91db-1d0b0f553863.png)

Description: This mass dropper is still work in progress so probably it’s disabled for further improvements.

**Comment by Sturdge** [comment]
Level boundary was too far forward
