### ISSUE TITLE
Random appearance of floor object for some reason (unless it’s some game mechanic)

### ISSUE THREAD

**Issue by APODICTIC** [Sturdge/Splash-Dash#218]
Name of Bug: Random appearance of floor object for some reason (unless it’s some game mechanic)

Type: Minor

Repeatable: Yes

Steps to Reproduce: 1. Open the game
                                     2. Select characters
                                     3. Select Fridge level
                                     4. Look for random object spawning at random place.

Screenshot: 

![image](https://user-images.githubusercontent.com/56399859/79765940-3a168280-831f-11ea-99f1-727ea64a2207.png)

Description: There is random spawning of object at random places throughout the scene. As you can see the purple floor type object near pineapple.

**Comment by Sturdge** [comment]
Those are the spawn points for the players, they just need to have their mesh renderer removed
