### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by APODICTIC** [Sturdge/Splash-Dash#219]
1.	Under options, only volume scroll is working and rest other aren’t working.
2.	Rematch button always load fridge level no matter which level you finished.
3.	Layouts aren’t loading randomly instead only one type of layout is loading for every level.

**Comment by Danny-HypnoTank** [comment]
Layout randomness works, other layouts need to be assigned to the pool of layouts

**Comment by Danny-HypnoTank** [comment]
rematch button loads the correct scene now, and volume sliders work correctly
