### ISSUE TITLE
Couldn’t see the characters as it move down

### ISSUE THREAD

**Issue by Chethan05** [Sturdge/Splash-Dash#222]
Name of the bug: Couldn’t see the characters
Date: 20/04/2020
Type: Minor
Repeatable: Yes
Steps to Reproduce:
•	Main Menu
•	Select Characters
•	Select Sink level
•	Play game
 
Description:
Couldn’t see the characters when the player move towards bottom of the scene.
![Screenshot (111)_LI](https://user-images.githubusercontent.com/56399911/79815386-8cd05880-8378-11ea-8b18-e667bce90136.jpg)

**Comment by Danny-HypnoTank** [comment]
Fix using cheet sink model once created and moving camera
