### ISSUE TITLE
Isn’t showing winner logo on Sink end game round scene

### ISSUE THREAD

**Issue by Chethan05** [Sturdge/Splash-Dash#223]
Name of the bug: Isn’t showing winner logo on Sink end game round scene
Date: 20/04/2020
Type: Minor
Repeatable: Yes
Steps to Reproduce:
•	Main Menu
•	Select Characters
•	Select Sink level
•	Play game
•	Finish game
 
Description:
Isn’t showing winner symbol on the end game scene for sink level.
![Screenshot (112)](https://user-images.githubusercontent.com/56399911/79815675-2861c900-8379-11ea-8210-1d9edda2e5a8.png)

**Comment by Danny-HypnoTank** [comment]
WInner logo was moved backwards has now been moved forwards
