### ISSUE TITLE
Layout Spawn Errors - Playtest 26/04/2020

### ISSUE THREAD

**Issue by Lokenplays** [Sturdge/Splash-Dash#234]
Issue - Multiple layouts not spawning

Description - Sink and Bin levels , with the sink being the worst culprit, would not spawn layouts. However due to conversation had during play test with Danny i believe this issue is resolved and will require further play testing to verify.

**Comment by Danny-HypnoTank** [comment]
Spawners were in the wrong position and have now been moved to work properly
